"""Match-flow charts (non-pitch): momentum by xT and a shot profile breakdown.

These mirror the summary panels seen on professional match reports. Same house
style as distributions.py / comparisons.py: theme colours only, graceful early
return on empty data, one ``chart(...)`` registration per figure. Because they
land in ``visual_registry`` they appear automatically in Open Play Studio (via
the registry bridge) and in the Players/Scouting visualization workspace.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from fap.visuals import analysis as A
from fap.visuals.maps._builders import chart

# shot-result vocab shared with the attacking maps
_ON_TARGET = ("goal", "saved", "on target", "on_target", "saved to post")
_OFF_TARGET = ("off target", "off_target", "wayward", "wide", "post", "off t")


# ------------------------------------------------------------------ momentum
def _momentum(ax, ctx) -> None:
    """Per-minute attacking threat (xT generated) for each team: the leading team's
    bars go up, the opponent's down - the classic momentum flow."""
    d = A.movement(ctx.df).dropna(subset=["x", "y", "end_x", "end_y"]).copy()
    if d.empty:
        return
    gain = A.xt_value(d["end_x"], d["end_y"]) - A.xt_value(d["x"], d["y"])
    d["_xt"] = np.clip(gain, 0, None)                     # only positive threat created
    d["_min"] = pd.to_numeric(d["minute"], errors="coerce")
    d["_team"] = d["team"].astype(str).str.strip()
    d = d[d["_min"].notna() & d["_team"].ne("")]
    if d.empty:
        return
    c = ctx.theme.colors
    order = d["_team"].value_counts().index.tolist()
    idx = np.arange(0, max(int(d["_min"].max()) + 1, 90) + 1)

    def per_minute(team: str) -> np.ndarray:
        sub = d[d["_team"] == team]
        s = sub.groupby(sub["_min"].astype(int))["_xt"].sum()
        return s.reindex(idx, fill_value=0.0).to_numpy()

    ax.bar(idx, per_minute(order[0]), width=0.9, label=str(order[0]),
           color=ctx.controls.get("primary_color") or c["accent"])
    if len(order) > 1:
        ax.bar(idx, -per_minute(order[1]), width=0.9, label=str(order[1]),
               color=ctx.controls.get("fail_color") or c["danger"])
    ax.axhline(0, color=c["grid"], lw=1.0)
    ax.set_xlabel("Minute")
    ax.set_ylabel("xT generated per minute")
    if ctx.controls.get("legend", True) and len(order) > 1:
        ax.legend(facecolor=c["panel"], edgecolor=c["grid"],
                  labelcolor=c["text"], fontsize=ctx.style("legend_size"))


chart("momentum_xt", "Match Momentum (xT)",
      lambda ctx, ax: _momentum(ax, ctx), category="Team",
      description="Per-minute xT generated by each team - who is on top, minute by minute.")


# ------------------------------------------------------------------ shot profile
def _shot_profile(ax, ctx) -> None:
    """Horizontal breakdown of shots by body part, outcome and situation. Splits by
    team when both are present, otherwise a single series (works for a scouting frame)."""
    shots = A.shots(ctx.df)
    if shots.empty:
        return
    bp = shots["body_part"].astype(str).str.lower()
    res = shots["shot_result"].astype(str).str.lower()
    sp = shots["set_piece"].astype(str).str.strip()
    cats: list[tuple[str, pd.Series]] = [
        ("Right foot", bp.eq("right foot")),
        ("Left foot", bp.eq("left foot")),
        ("Head", bp.str.contains("head", na=False)),
        ("Goal", res.eq("goal")),
        ("On target", res.isin(_ON_TARGET)),
        ("Off target", res.isin(_OFF_TARGET)),
        ("Blocked", res.eq("blocked")),
        ("Open play", sp.eq("")),
        ("Set piece", sp.ne("")),
    ]
    labels = [name for name, _ in cats]
    c = ctx.theme.colors
    teams = shots["team"].astype(str).str.strip()
    present = [t for t in teams.value_counts().index.tolist() if t]
    y = np.arange(len(cats))

    if len(present) >= 2:
        a, b = present[0], present[1]
        va = [int(mask[teams.eq(a)].sum()) for _, mask in cats]
        vb = [int(mask[teams.eq(b)].sum()) for _, mask in cats]
        ax.barh(y + 0.2, va, height=0.4, label=str(a),
                color=ctx.controls.get("primary_color") or c["accent"])
        ax.barh(y - 0.2, vb, height=0.4, label=str(b),
                color=ctx.controls.get("fail_color") or c["danger"])
        if ctx.controls.get("legend", True):
            ax.legend(facecolor=c["panel"], edgecolor=c["grid"],
                      labelcolor=c["text"], fontsize=ctx.style("legend_size"))
    else:
        ax.barh(y, [int(mask.sum()) for _, mask in cats],
                color=ctx.controls.get("primary_color") or c["accent"])

    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.invert_yaxis()
    ax.set_xlabel("Shots")


chart("shot_profile", "Shot Profile",
      lambda ctx, ax: _shot_profile(ax, ctx), category="Attacking",
      description="Shots broken down by body part, outcome and situation (team-split "
                  "when both teams are present).")
